package IHM;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextArea;

import Models.LocalUser;
import Models.User;
import TheFuckingNetwork.CommunicaTCPClient;
import TheFuckingNetwork.CommunicaTCPServer;
import TheFuckingNetwork.Conversation;

/**
 *
 * @author Aymane
 */
public class ChatFrame extends javax.swing.JFrame {

	CommunicaTCPServer tcpServ=null;
	LocalUser localUser;
    /**
     * Creates new form NewJFrame
     */
	public ChatFrame(LocalUser lu){
		this();
		this.localUser=lu;
		
	}
	public void setTcpServ(CommunicaTCPServer tcpServ){
		this.tcpServ=tcpServ;
	}
    public ChatFrame() {
    	
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	chatPanels = new ArrayList<JPanel>();
    	conversations = new ArrayList<Conversation>();
    	model = new DefaultListModel<User>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        list1 = new JList(model);
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
     //   jPanel6 = new javax.swing.JPanel();
      
     
        jPanel8 = new javax.swing.JPanel();
        textField5 = new java.awt.TextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversations");
        setAlwaysOnTop(true);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Table.selectionInactiveBackground"));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Disconnect");
        jButton1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

      
//        list1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                list1ActionPerformed(evt);
//            }
//        });

        jLabel2.setBackground(new java.awt.Color(255, 51, 102));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("         Connected users:");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(581, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        

       


       
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)))
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
   
        pack();
    // </editor-fold>                        


	list1.addMouseListener(new MouseAdapter() {
	    public void mouseClicked(MouseEvent evt) {
	        JList list = (JList)evt.getSource();
	        if (evt.getClickCount() >= 2) {
	            // Double-click detected
	            User u = (User)list.getSelectedValue();
	            System.out.println("Double click detected "+u.getPseudo());
	                        	
	            	startConversationToDistantUser(u);
	            

	        } 
	    }
	});
    }
    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        System.out.println("Action performed !");
    }                                     

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
//    
//   
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
  
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
  
    private javax.swing.JTextPane jTextPane5;
    private JList list1;
    
    private java.awt.TextField textField5;
    public DefaultListModel<User> model;
    public ArrayList<Conversation> conversations;
    public ArrayList<JPanel> chatPanels;
    
	 public DefaultListModel<User> getListModel(){
		  return this.model;
	  }
	 
	 //Todo: This.
	 public void endConversation(Conversation c){}
	 public void endConversation(JPanel jp){
		 jTabbedPane2.remove(jp);
	 }
	 public ConversationPanelElements startConversation(Conversation c){ 
		 ConversationPanelElements cpe = new ConversationPanelElements(c);
		 c.addConversationPanelElements(cpe);
		 return cpe;
	 }
	 public void startConversationToDistantUser(User u){
		 try{
			 
			 CommunicaTCPClient cli = new CommunicaTCPClient(4450, InetAddress.getByName("localhost"), u.getPort(), u.getPseudo(),tcpServ);
			 Conversation c = cli.getTcpClientConversation();
			 System.err.println("Client inited..");
			 try{Thread.sleep(200);}catch (InterruptedException e) {}
			 ConversationPanelElements cpe = startConversation(c);
			 cpe.remoteUserSendMessage("You started a conversation with "+c.getUsersInConversation());
			 //Check some port fuckery
			 //Roll the dices
			 //Profit
			 
		 } catch (UnknownHostException e) {	System.out.println("Unknown Host");
			e.printStackTrace();
		}
	 }
	

public class ConversationPanelElements {
	  private javax.swing.JTextPane jTextPane3;
	  private Conversation c;
	  private javax.swing.JScrollPane jScrollPane3;
	  private javax.swing.JTextField jtextField3;
	  private javax.swing.JButton jButton3;
	  private javax.swing.JButton jButton2;
	  private  JPanel jPanel6;
	  String chat = "";
	  
	public ConversationPanelElements(Conversation c){
		//Init of compos
		this.c = c;
		
		  jtextField3 = new javax.swing.JTextField();	      
	      jScrollPane3 = new javax.swing.JScrollPane();
	      jTextPane3 = new javax.swing.JTextPane();
	      jPanel6 = new JPanel();
	      jButton3 = new javax.swing.JButton();
	      jButton2 = new javax.swing.JButton();
	      jPanel6.setName(c.getID());
			 
	      setComponents();
	}
	
	public void localUserSendMessage(String s){
		chat+="You: "+ s+"\n";
		c.sendMessage(s);
		this.jTextPane3.setText(chat);
		
	}
	public void remoteUserSendMessage(String s){
		chat+=s+"\n";
		this.jTextPane3.setText(chat);
		
	}

	private void setComponents(){
		 conversations.add(c);
		 String remoteUser;
		 
		 
		
		
		
		 
		   jtextField3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jtextField3ActionPerformed(evt);
	            }

				private void jtextField3ActionPerformed(ActionEvent evt) {
					localUserSendMessage(jtextField3.getText());
	            	jtextField3.setText("");
	          
				}
	        });
	
		 
		 jButton3.setText("Send");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	               // jButton3ActionPerformed(evt);
	            	localUserSendMessage(jtextField3.getText());
	            	jtextField3.setText("");
	            	
	            	
	            }
	        });
	        
	               
	        
//	        new GhostText(JtextField3, "Your message...");
//	        JtextField3.addActionListener(new java.awt.event.ActionListener() {
//	            public void actionPerformed(java.awt.event.ActionEvent evt) {
//	                textField3ActionPerformed(evt);
//	            }
//	        });

	        jScrollPane3.setViewportView(jTextPane3);
	        
	        
	        jButton2.setBackground(new java.awt.Color(255, 204, 153));
	        jButton2.setText("Quit this conv.");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	               // jButton3ActionPerformed(evt);
	            	endConversation(jPanel6);
	            }
	        });
	        jButton2.setToolTipText("");
	        
		 javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
	        jPanel6.setLayout(jPanel6Layout);
	        jPanel6Layout.setHorizontalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addComponent(jtextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton3)
	                .addContainerGap())
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jButton2)
	                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(0, 0, Short.MAX_VALUE))
	        );
	        jPanel6Layout.setVerticalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
	                .addComponent(jButton2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jtextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
	                        .addComponent(jButton3)
	                        .addGap(14, 14, 14)))
	                .addContainerGap())
	        );
	        
	        
	        jPanel6.setBackground(new java.awt.Color(212, 232, 252));
	        
	        
	        chatPanels.add(jPanel6);
	        remoteUser =c.getUsersInConversation();
	        System.err.println("Users in conv at panel init: "+remoteUser);
	        jTabbedPane2.addTab(remoteUser, jPanel6);
		
	}
	}



}
